version: "3.9"

services: 
    book-management:
        container_name: back-end
        build: ./
        command: npm start
        working_dir: /urs/my-app/book-management
        ports: 
            - "3009:3009"
        volumes: 
            - ./:/urs/my-app/book-management
    mysql:
        container_name: mysql
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: Library_Book
            MYSQL_USER: root
            MYSQL_PASSWORD: vanhung1999
            MYSQL_ROOT_PASSWORD: vanhung1999
            volumes:
                - ./docker/mysql/dbdata:/var/lib/mysql
            networks:
                - learning-network